2008-06-15 Erwann Chenede - <erwann.chenede@sun.com>
  * desktop-mime-cache/desktop-mime-cache
  * desktop-mime-cache/desktop-mime-cache.xml
  * gconf-cache/gconf-cache :
    added minor changes suggested by David Bustos



git-svn-id: file:///export/mirror/svn/svn.opensolaris.org/svn/jds/desktop-cache/trunk@21 080c96c5-abdd-cfe1-8e51-841d7e5cfe93

diff --git a/desktop-mime-cache/desktop-mime-cache b/desktop-mime-cache/desktop-mime-cache
--- a/desktop-mime-cache/desktop-mime-cache
+++ b/desktop-mime-cache/desktop-mime-cache
@@ -67,11 +67,13 @@ esac
 # generate the cache
 #
 
+MIMEFILE="/usr/share/applications/mimeinfo.cache"
+
 IFS=" 
 "
-if [ -a "/usr/share/applications/mimeinfo.cache" ]; then
+if [ -a $MIMEFILE ]; then
   RESULT=`/usr/bin/find /usr/share/applications ! -type d -follow \
-    -newer /usr/share/applications/mimeinfo.cache -print 2>/dev/null`
+    -newer $MIMEFILE -print 2>/dev/null`
 else
   RESULT="no cache found"
 fi
@@ -80,10 +82,10 @@ if [ -n "$RESULT" ]; then
   echo "updating desktop file cache" 
   /usr/bin/update-desktop-database
   if [ $? -ne 0 ]; then
-    echo "update-mime-database exited with an error while generating the desktop file cache /usr/share/applications/mimeinfo.cache"
-    exit $SMF_EXIT_MON_DEGRADE
+    echo "update-mime-database exited with an error while generating the desktop file cache $MIMEFILE"
+    exit $SMF_EXIT_ERR_FATAL
   else
-    echo "desktop file cache /usr/share/applications/mimeinfo.cache generated"
+    echo "desktop file cache $MIMEFILE generated"
   fi
 fi
 
